version: '3.9'
services:
  node:
    build: .
    command: npm start
    volumes:
      # - type: bind
      #   source: ./src/server.ts
      #   target: /docker/src/server.ts
      - ./src:/docker/src
      - logs:/docker/logs
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    networks:
      - net
  postgres:
    build: ./postgres
    # volumes:
      # - db_data:node_modules/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24

volumes:
  logs:
#   db-data:
