version: '3.9'
services:
  node:
    build: .
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    links:
      - postgres
  postgres:
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}