version: '3.9'
services:
  node:
    build: .
    command: npm start
    volumes:
      # - type: bind
      #   source: ./src/server.ts
      #   target: /docker/src/server.ts
      - ./src:/docker/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    networks:
      - net
  postgres:
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
